name: Build & Download Docker Image

on:
  # 允许手动触发
  workflow_dispatch:
  # 每次推送到 main 分支自动触发
  push:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. 构建镜像 (强制指定 linux/amd64，适配你的 VPS)
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # 这里的 false 表示不推送到网上，只在本地构建
          push: false
          # 强制构建为 VPS 通用的架构
          platforms: linux/amd64
          tags: my-dianshi:latest
          # 这一步是为了让后续的 docker save 能找到镜像
          outputs: type=docker,dest=/tmp/my-dianshi.tar

      # 2. 压缩文件 (减小体积，方便你下载)
      - name: Compress Image
        run: |
          gzip /tmp/my-dianshi.tar

      # 3. 上传到 GitHub 页面供你下载
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-file
          path: /tmp/my-dianshi.tar.gz
          retention-days: 3
